name: "Validate Flags"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
  workflow_dispatch:

jobs:
  validate-flags:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for git branch comparison

      # Automatically compares against PR base branch (main)
      - name: Compare against base branch
        uses: open-feature/action@v0.0.6
        with:
          manifest: "flags.json"
          post-pr-comment: false

      - name: debugging
        run: cat flags.json && cat against-flags.json

      - name: Compare against remote manifest
      # Secret not accessible for PRs from forks
        if: github.repository == github.event.repository.full_name
        uses: open-feature/action@v0.0.6
        with:
          manifest: "flags.json"
          against: "https://flagd-studio.onrender.com/api"
          auth-token: ${{ secrets.FLAGD_STUDIO_TOKEN }}

      - name: debugging
        run: cat flags.json && cat against-flags.json
